<a href="https://colab.research.google.com/github/Ananthu19-20/GRIPSEPT23/blob/main/Academic_Mark_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
# Load the dataset
df=pd.read_csv("/content/Class VII  (2).csv")

# Display the first few rows of the dataset
df.head(10)

,Student ID,Section,Total Study Hours,Attendence,EPT-1(25),EPT-2(25),ETerm 1(50),EPT-3(25),EPT-4(25),ETerm 2(40),...,SSPT-2(25),SSTerm 1(50),SSPT-3(25),SSPT-4(25),SSTerm 2(40),SSInternals(10),SSPT weigtage,SSTerm 1 Weightage,SSFinal Term weightage,SSTW
0,1,A,4,98,7,7,18,3,2,20,...,4,14,5,3,6,8,0.90,4.90,5.6,11
1,2,A,5,84,17,11,28,14,13,29,...,13,32,10,19,25,8,3.10,11.20,13.2,28
2,3,A,4,93,10,10,22,3,5,20,...,13,17,11,8,16,8,2.50,5.95,9.6,18
3,4,A,3,88,12,18,31,15,13,26,...,19,30,19,21,25,9,4.05,10.50,13.6,28
4,5,A,5,91,14,12,29,9,9,21,...,19,29,14,18,23,9,3.50,10.15,12.8,26
5,6,A,5,92,14,15,31,13,14,28,...,22,40,21,25,36,9,4.55,14.00,18.0,37
6,7,A,5,90,14,15,28,16,11,25,...,18,37,23,22,36,9,3.85,12.95,18.0,35
7,8,A,3,89,16,12,30,14,14,25,...,19,34,15,21,31,9,3.30,11.90,16.0,31
8,9,A,4,89,13,11,22,10,9,18,...,10,30,12,15,25,8,2.25,10.50,13.2,26
9,10,A,3,99,11,10,19,11,9,25,...,8,25,12,15,22,8,2.60,8.75,12.0,23

In [5]:
# Getting information about the dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 81 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Student ID              156 non-null    int64
 1   Section                 156 non-null    object
 2   Total Study Hours       156 non-null    int64
 3   Attendence              156 non-null    int64
 4   EPT-1(25)               156 non-null    int64
 5   EPT-2(25)               156 non-null    int64
 6   ETerm 1(50)             156 non-null    int64
 7   EPT-3(25)               156 non-null    int64
 8   EPT-4(25)               156 non-null    int64
 9   ETerm 2(40)             156 non-null    int64
 10  EInternals(10)          156 non-null    int64
 11  EPT weigtage            156 non-null    float64
 12  ETerm 1 Weightage       156 non-null    float64
 13  EFinal Term weightage   156 non-null    float64
 14  ETW                     156 non-null    int64
 15  MPT-1(25)               156 non-null    int64
 16  MPT-2(25)               156 non-null    int64
 17  MTerm 1(50)             156 non-null    int64
 18  MPT-3(25)               156 non-null    int64
 19  MPT-4(25)               156 non-null    int64
 20  MTerm 2(40)             156 non-null    int64
 21  MInternals(10)          156 non-null    int64
 22  MPT weigtage            156 non-null    float64
 23  MTerm 1 Weightage       156 non-null    float64
 24  MFinal Term weightage   156 non-null    float64
 25  MTW                     156 non-null    int64
 26  HPT-1(25)               156 non-null    int64
 27  HPT-2(25)               156 non-null    int64
 28  HTerm 1(50)             156 non-null    int64
 29  HPT-3(25)               156 non-null    int64
 30  HPT-4(25)               156 non-null    int64
 31  HTerm 2(40)             156 non-null    int64
 32  HInternals(10)          156 non-null    int64
 33  HPT weigtage            156 non-null    float64
 34  HTerm 1 Weightage       156 non-null    float64
 35  HFinal Term weightage   156 non-null    float64
 36  HTW                     156 non-null    int64
 37  MtPT-1(25)              156 non-null    int64
 38  MtPT-2(25)              156 non-null    int64
 39  MtTerm 1(50)            156 non-null    int64
 40  MtPT-3(25)              156 non-null    int64
 41  MtPT-4(25)              156 non-null    int64
 42  MtTerm 2(40)            156 non-null    int64
 43  MtInternals(10)         156 non-null    int64
 44  MtPT weigtage           156 non-null    float64
 45  MtTerm 1 Weightage      156 non-null    float64
 46  MtFinal Term weightage  156 non-null    float64
 47  MtTW                    156 non-null    int64
 48  SPT-1(25)               156 non-null    float64
 49  SPT-2(25)               156 non-null    int64
 50  STerm 1(50)             156 non-null    int64
 51  SPT-3(25)               156 non-null    int64
 52  SPT-4(25)               156 non-null    int64
 53  STerm 2(40)             156 non-null    int64
 54  SInternals(10)          156 non-null    int64
 55  SPT weigtage            156 non-null    float64
 56  STerm 1 Weightage       156 non-null    float64
 57  SFinal Term weightage   156 non-null    float64
 58  STW                     156 non-null    int64
 59  CSPT-1(25)              156 non-null    int64
 60  CSPT-2(25)              156 non-null    int64
 61  CSTerm 1(50)            156 non-null    int64
 62  CSPT-3(25)              156 non-null    int64
 63  CSPT-4(25)              156 non-null    int64
 64  CSTerm 2(40)            156 non-null    int64
 65  CSInternals(10)         156 non-null    int64
 66  CSPT weigtage           156 non-null    float64
 67  CSTerm 1 Weightage      156 non-null    float64
 68  CSFinal Term weightage  156 non-null    float64
 69  CSTW                    156 non-null    int64
 70  SSPT-1(25)              156 non-null    int64
 71  SSPT-2(25)              156 non-null    int64
 72  SSTerm 1(50)            156 non-null    int64
 73  SSPT-3(25)              156 non-null    int64
 74  SSPT-4(25)              156 non-null    int64
 75  SSTerm 2(40)            156 non-null    int64
 76  SSInternals(10)         156 non-null    int64
 77  SSPT weigtage           156 non-null    float64
 78  SSTerm 1 Weightage      156 non-null    float64
 79  SSFinal Term weightage  156 non-null    float64
 80  SSTW                    156 non-null    int64
dtypes: float64(22), int64(58), object(1)
memory usage: 98.8+ KB

In [6]:
# Descriptive statistics of the dataset

df.describe()

,Student ID,Total Study Hours,Attendence,EPT-1(25),EPT-2(25),ETerm 1(50),EPT-3(25),EPT-4(25),ETerm 2(40),EInternals(10),...,SSPT-2(25),SSTerm 1(50),SSPT-3(25),SSPT-4(25),SSTerm 2(40),SSInternals(10),SSPT weigtage,SSTerm 1 Weightage,SSFinal Term weightage,SSTW
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,...,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000
mean,78.500000,3.974359,89.660256,15.391026,15.621795,32.608974,12.602564,13.474359,27.269231,8.576923,...,16.673077,30.910256,14.333333,16.891026,27.487179,8.250000,3.255769,10.818590,14.294872,28.397436
std,45.177428,0.786570,5.553838,4.315873,4.826463,8.216093,5.494489,5.312734,7.115042,1.734055,...,6.061154,12.399985,6.289093,7.092544,8.519039,1.412502,1.168801,4.339995,3.893316,9.099223
min,1.000000,3.000000,80.000000,4.000000,5.000000,12.000000,2.000000,2.000000,3.000000,5.000000,...,2.000000,3.000000,2.000000,1.000000,2.000000,5.000000,0.650000,1.050000,2.800000,5.000000
25%,39.750000,3.000000,86.000000,12.000000,12.000000,28.000000,9.000000,9.000000,22.000000,8.000000,...,13.000000,21.000000,9.750000,11.000000,23.000000,8.000000,2.450000,7.350000,12.300000,22.000000
50%,78.500000,4.000000,89.000000,16.000000,16.000000,32.000000,12.000000,14.000000,27.000000,9.000000,...,19.000000,34.000000,14.000000,19.000000,30.000000,8.500000,3.450000,11.900000,15.400000,31.000000
75%,117.250000,5.000000,94.000000,19.000000,19.000000,39.000000,17.000000,17.000000,33.000000,10.000000,...,21.000000,41.000000,19.250000,24.000000,34.000000,9.000000,4.212500,14.350000,17.300000,36.000000
max,156.000000,5.000000,100.000000,23.000000,25.000000,48.000000,25.000000,24.000000,40.000000,10.000000,...,25.000000,50.000000,25.000000,25.000000,40.000000,10.000000,4.950000,17.500000,20.000000,42.000000

In [7]:
# Identify columns containing "AB"
columns_with_ab = []

# Loop through all columns to check for "AB"
for col in df.columns:
    if df[col].astype(str).str.contains('AB').any():
        columns_with_ab.append(col)

# Print the columns with "AB"
print("Columns containing 'AB':")
print(columns_with_ab)

Columns containing 'AB':
[]

In [9]:
# import pandas as pd
# import numpy as np

# # Replace "AB" with NaN
# df.replace("AB", np.nan, inplace=True)

# # Define subject-wise column ranges
# subjects = {
#     "English": ["EPT-1(25)", "ETW"],
#     "Malayalam": ["MPT-1(25)", "MTW"],
#     "Hindi": ["HPT-1(25)", "HTW"],
#     "Mathematics": ["MtPT-1(25)", "MtTW"],
#     "Science": ["SPT-1(25)", "STW"],
#     "Computer Science": ["CSPT-1(25)", "CSTW"],
#     "Social Science": ["SSPT-1(25)", "SSTW"]
# }

# # Function to drop rows based on NaN values within the specified range of columns
# def drop_rows_with_nan_in_range(df, start_col, end_col):
#     start_idx = df.columns.get_loc(start_col)
#     end_idx = df.columns.get_loc(end_col) + 1
#     subject_columns = df.columns[start_idx:end_idx]
#     return df.dropna(subset=subject_columns, how="any")

# # Apply the function for each subject
# for subject, (start_col, end_col) in subjects.items():
#     df = drop_rows_with_nan_in_range(df, start_col, end_col)
#     print(f"Rows with NaN in {subject} columns dropped.")

# # Reset index after row removals
# df.reset_index(drop=True, inplace=True)

# # Display the updated DataFrame
# print("Updated DataFrame after dropping rows:")
# print(df)

In [8]:
# Shape of the dataset (number of rows and columns)

df.shape

(156, 81)

In [10]:
# Convert 'object' columns with numerical entries to numeric
for col in df.columns:
    if df[col].dtype == 'object':
        try:
            df[col] = pd.to_numeric(df[col], errors='coerce')
        except Exception as e:
            print(f"Error in column {col}: {e}")

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder

In [12]:
def score_range(x):
    if x == 45:
        return '190-200'
    elif x >= 40:
        return '180-189'
    elif x >= 35:
        return '170-179'
    elif x >= 30:
        return '160-169'
    elif x >= 25:
        return '150-159'
    else:
        return 'Below 150'

# Apply score ranges for each subject
df['ETW_range'] = df['ETW'].apply(score_range)
df['MTW_range'] = df['MTW'].apply(score_range)
df['HTW_range'] = df['HTW'].apply(score_range)
df['MtTW_range'] = df['MtTW'].apply(score_range)
df['STW_range'] = df['STW'].apply(score_range)
df['CSTW_range'] = df['CSTW'].apply(score_range)
df['SSTW_range'] = df['SSTW'].apply(score_range)

In [13]:
# Combine all ranges for prediction (multi-targets)
subject_targets = ['ETW_range', 'MTW_range', 'HTW_range', 'MtTW_range', 'STW_range', 'CSTW_range', 'SSTW_range']

In [14]:
# Encode target variables
le = LabelEncoder()
for target in subject_targets:
    df[target] = le.fit_transform(df[target])

# Features (X) - drop non-numeric IDs and targets
targets = df[subject_targets]
X = df.drop(columns=['Student ID'] + subject_targets)

In [15]:
# Split the Dataset
X_train, X_test, y_train, y_test = train_test_split(X, targets, test_size=0.2, random_state=42)

In [16]:
# Train Random Forest Classifier
rf_models = {}
rf_predictions = {}
accuracy_scores = {}

for subject in subject_targets:
    print(f"Training model for {subject}...")
    rf = RandomForestClassifier(n_estimators=100, random_state=42)
    rf.fit(X_train, y_train[subject])
    y_pred = rf.predict(X_test)

    rf_models[subject] = rf
    rf_predictions[subject] = y_pred
    accuracy_scores[subject] = accuracy_score(y_test[subject], y_pred)

    print(f"Accuracy for {subject}: {accuracy_scores[subject]:.2f}")
    print(classification_report(y_test[subject], y_pred, target_names=le.classes_))

Training model for ETW_range...
Accuracy for ETW_range: 0.84
              precision    recall  f1-score   support

     150-159       0.57      1.00      0.73         4
     160-169       0.90      0.75      0.82        12
     170-179       0.86      0.86      0.86         7
     180-189       1.00      0.50      0.67         2
   Below 150       1.00      1.00      1.00         7

    accuracy                           0.84        32
   macro avg       0.87      0.82      0.81        32
weighted avg       0.88      0.84      0.85        32

Training model for MTW_range...
Accuracy for MTW_range: 0.97
              precision    recall  f1-score   support

     150-159       1.00      1.00      1.00         4
     160-169       0.83      1.00      0.91         5
     170-179       1.00      0.90      0.95        10
     180-189       1.00      1.00      1.00         3
   Below 150       1.00      1.00      1.00        10

    accuracy                           0.97        32
   macro avg       0.97      0.98      0.97        32
weighted avg       0.97      0.97      0.97        32

Training model for HTW_range...
Accuracy for HTW_range: 0.97
              precision    recall  f1-score   support

     150-159       1.00      1.00      1.00         6
     160-169       1.00      0.67      0.80         3
     170-179       0.89      1.00      0.94         8
     180-189       1.00      1.00      1.00         3
   Below 150       1.00      1.00      1.00        12

    accuracy                           0.97        32
   macro avg       0.98      0.93      0.95        32
weighted avg       0.97      0.97      0.97        32

Training model for MtTW_range...
Accuracy for MtTW_range: 0.88
              precision    recall  f1-score   support

     150-159       1.00      0.80      0.89         5
     160-169       0.67      0.80      0.73         5
     170-179       0.67      0.80      0.73         5
     180-189       0.00      0.00      0.00         1
   Below 150       1.00      1.00      1.00        16

    accuracy                           0.88        32
   macro avg       0.67      0.68      0.67        32
weighted avg       0.86      0.88      0.87        32

Training model for STW_range...

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Accuracy for STW_range: 0.84
              precision    recall  f1-score   support

     150-159       0.71      0.62      0.67         8
     160-169       0.57      1.00      0.73         4
     170-179       1.00      0.89      0.94         9
     180-189       1.00      1.00      1.00         2
   Below 150       1.00      0.89      0.94         9

    accuracy                           0.84        32
   macro avg       0.86      0.88      0.86        32
weighted avg       0.88      0.84      0.85        32

Training model for CSTW_range...
Accuracy for CSTW_range: 0.91
              precision    recall  f1-score   support

     150-159       1.00      0.62      0.77         8
     160-169       0.60      1.00      0.75         3
     170-179       1.00      1.00      1.00        12
     180-189       1.00      1.00      1.00         5
   Below 150       0.80      1.00      0.89         4

    accuracy                           0.91        32
   macro avg       0.88      0.93      0.88        32
weighted avg       0.94      0.91      0.90        32

Training model for SSTW_range...
Accuracy for SSTW_range: 0.88
              precision    recall  f1-score   support

     150-159       0.00      0.00      0.00         3
     160-169       0.62      0.83      0.71         6
     170-179       0.89      1.00      0.94         8
     180-189       1.00      1.00      1.00         2
   Below 150       1.00      1.00      1.00        13

    accuracy                           0.88        32
   macro avg       0.70      0.77      0.73        32
weighted avg       0.81      0.88      0.84        32

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [17]:
# Summarize Results
print("\nModel Accuracy Summary:")
for subject, acc in accuracy_scores.items():
    print(f"{subject}: {acc:.2f}")

Model Accuracy Summary:
ETW_range: 0.84
MTW_range: 0.97
HTW_range: 0.97
MtTW_range: 0.88
STW_range: 0.84
CSTW_range: 0.91
SSTW_range: 0.88

In [18]:
import pickle
pickle.dump(rf_models['ETW_range'], open('ETW_model.pkl', 'wb'))
pickle.dump(le, open('ETW_label_encoder.pkl', 'wb'))

In [19]:
pickle.dump(rf_models['MTW_range'], open('MTW_model.pkl', 'wb'))
pickle.dump(le, open('MTW_label_encoder.pkl', 'wb'))

In [20]:
pickle.dump(rf_models['HTW_range'], open('HTW_model.pkl', 'wb'))
pickle.dump(le, open('HTW_label_encoder.pkl', 'wb'))

In [22]:
pickle.dump(rf_models['MtTW_range'], open('MtTW_model.pkl', 'wb'))
pickle.dump(le, open('MtTW_label_encoder.pkl', 'wb'))

In [23]:
pickle.dump(rf_models['STW_range'], open('STW_model.pkl', 'wb'))
pickle.dump(le, open('STW_label_encoder.pkl', 'wb'))

In [24]:
pickle.dump(rf_models['CSTW_range'], open('CSTW_model.pkl', 'wb'))
pickle.dump(le, open('CSTW_label_encoder.pkl', 'wb'))

In [26]:
pickle.dump(rf_models['SSTW_range'], open('SSTW_model.pkl', 'wb'))
pickle.dump(le, open('SSTW_label_encoder.pkl', 'wb'))